### ISSUE TITLE
moduletool package warns about unpackaged pyc files

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta-core#3178]
The `moduletool package` command warns about any files that were not included in the package. It should exclude `*.pyc` files from this warning. Here's an example warning:
```
WARNING  inmanta.moduletool:moduletool.py:755 The following files are present in the inmanta_plugins/minimalv2module directory on disk, but were not packaged: ['__pycache__/__init__.cpython-39.pyc']. Update you setup.cfg file if they need to be packaged.
```

**Comment by wouterdb** [comment]
should be fixed

**Comment by sanderr** [comment]
Not fixed yet. Only `__pycache__` and `__cfcache__` are currently ignored.
